const express=require("express"),multer=require("multer"),path=require("path"),fs=require("fs"),http=require("http"),crypto=require("crypto"),{WebSocketServer}=require("ws");let nodemailer=null;try{nodemailer=require("nodemailer")}catch{}const autoDJ=require("./radio/autodj"),live=require("./radio/live"),broadcast=require("./radio/broadcast");
const app=express(),PORT=process.env.PORT||3000,ROOT=__dirname,ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"",AUTH_SECRET=process.env.AUTH_SECRET||crypto.randomBytes(32).toString("hex");app.use(express.json());app.use(express.urlencoded({extended:true}));app.use((req,res,next)=>{res.setHeader("Access-Control-Allow-Origin",req.headers.origin||"*");res.setHeader("Vary","Origin");res.setHeader("Access-Control-Allow-Methods","GET,POST,DELETE,OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type, Authorization");res.setHeader("Access-Control-Allow-Credentials","true");if(req.method==="OPTIONS")return res.sendStatus(204);next()});
const MEDIA_ROOT=process.env.MEDIA_ROOT?path.resolve(process.env.MEDIA_ROOT):ROOT;const MUSIC=path.join(MEDIA_ROOT,"music"),ADS=path.join(MEDIA_ROOT,"ads"),JINGLES=path.join(MEDIA_ROOT,"jingles");[MUSIC,ADS,JINGLES].forEach(d=>fs.mkdirSync(d,{recursive:true}));
function storage(dir){return multer.diskStorage({destination:dir,filename:(req,file,cb)=>{const safe=path.basename(file.originalname).replace(/[^a-zA-Z0-9._-]/g,"_");cb(null,Date.now()+"-"+safe)}})}
function media(dir,field){return multer({storage:storage(dir),limits:{fileSize:50*1024*1024},fileFilter:(r,f,cb)=>cb(null,[".mp3",".wav",".m4a"].includes(path.extname(f.originalname).toLowerCase())||String(f.mimetype).startsWith("audio/"))}).array(field,20)}
function makeToken(){const body=Buffer.from(JSON.stringify({exp:Date.now()+8*60*60*1000})).toString("base64url");const sig=crypto.createHmac("sha256",AUTH_SECRET).update(body).digest("base64url");return body+"."+sig}
function validToken(t){try{const [body,sig]=String(t||"").split(".");if(!body||!sig)return false;const good=crypto.createHmac("sha256",AUTH_SECRET).update(body).digest("base64url");return crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(good))&&JSON.parse(Buffer.from(body,"base64url")).exp>Date.now()}catch{return false}}
function requireAdmin(req,res,next){if(validToken((req.headers.authorization||"").replace(/^Bearer\s+/i,"")))return next();return res.status(401).json({success:false,error:"Admin login required"})}
app.post("/api/auth/login",(req,res)=>{const p=String(req.body?.password||"");if(!ADMIN_PASSWORD)return res.status(503).json({success:false,error:"Admin password is not configured on the server. Set ADMIN_PASSWORD in Render Environment Variables and redeploy."});if(p!==ADMIN_PASSWORD)return res.status(401).json({success:false,error:"Invalid password"});res.json({success:true,token:makeToken()})});
app.get("/api/auth/status",(req,res)=>res.json({success:true,passwordConfigured:Boolean(ADMIN_PASSWORD)}));
app.get("/api/auth/check",requireAdmin,(req,res)=>res.json({success:true}));
app.get("/health",(q,s)=>s.json({success:true,service:"JON RADIO PLATFORM",status:"ONLINE",version:"2.0"}));app.get("/",(q,s)=>s.json({platform:"JON RADIO PLATFORM",station:"JON FM ETHIOPIA",status:"ONLINE",version:"2.0"}));
app.use("/music",express.static(MUSIC));app.use("/ads",express.static(ADS));app.use("/jingles",express.static(JINGLES));
let monitorLastError=null,monitorLastAlertAt=0,monitorLastOnline=null;function stationHealth(){const d=autoDJ.getStatus(),b=broadcast.status(),online=Boolean(b.running&&(d.live||d.autoDJ||live.isActive()));let reason=null;if(!online)reason="Radio stream is offline";else if(d.autoDJ&&!d.live&&!d.ffmpegRunning)reason="Auto DJ FFmpeg is not running";return{online,nowPlaying:d.nowPlaying||null,listeners:b.listeners,uptimeSeconds:Math.floor(process.uptime()),uptime:Math.floor(process.uptime()),ffmpegRunning:Boolean(d.ffmpegRunning||live.isActive()),lastOutputAt:d.lastOutputAt||null,lastError:monitorLastError||null,reason,source:b.source,checkedAt:new Date().toISOString()}}\nasync function sendHealthAlert(h){const host=process.env.SMTP_HOST,to=process.env.ALERT_EMAIL_TO,from=process.env.ALERT_EMAIL_FROM||process.env.SMTP_USER;if(!nodemailer||!host||!to||!process.env.SMTP_USER||!process.env.SMTP_PASS||!from)return false;const now=Date.now();if(now-monitorLastAlertAt<10*60*1000)return false;monitorLastAlertAt=now;try{const transporter=nodemailer.createTransport({host,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE)==="true",auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});await transporter.sendMail({from,to,subject:h.online?"JON FM Radio ONLINE":"JON FM Radio OFFLINE",text:h.online?"JON FM Ethiopia radio is back ONLINE.\\nNow Playing: "+(h.nowPlaying||"—")+"\\nListeners: "+h.listeners:"JON FM Ethiopia radio is OFFLINE.\\nReason: "+(h.reason||"Unknown")+"\\nLast error: "+(h.lastError||"None")});return true}catch(e){monitorLastError="Alert email failed: "+e.message;return false}}app.get("/api/status",(q,s)=>{const d=autoDJ.getStatus(),b=broadcast.status();s.json({station:"JON FM ETHIOPIA",online:b.running,live:d.live||live.isActive(),autoDJ:d.autoDJ,listeners:b.listeners,nowPlaying:d.nowPlaying,nextSong:d.nextSong,previousSong:d.previousSong,musicCount:d.musicCount,playlist:d.playlist,queue:d.queue,shuffle:d.shuffle,repeat:d.repeat,crossfade:d.crossfade,gain:d.gain,adInterval:d.adInterval,source:b.source,health:stationHealth()})});app.get("/api/health/monitor",async(q,s)=>{const h=stationHealth();if(monitorLastOnline!==null&&h.online!==monitorLastOnline)await sendHealthAlert(h);monitorLastOnline=h.online;s.status(h.online?200:503).json({success:true,health:h,alertEmailConfigured:Boolean(process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS&&process.env.ALERT_EMAIL_TO)});});
app.get("/api/music",(q,s)=>{const out=autoDJ.getMusicFiles().map(name=>{const st=fs.statSync(path.join(MUSIC,name));return{name,size:st.size,url:"/music/"+encodeURIComponent(name)}});s.json(out)});
const up=multer({storage:storage(MUSIC),limits:{fileSize:50*1024*1024},fileFilter:(r,f,cb)=>cb(null,[".mp3",".wav",".m4a"].includes(path.extname(f.originalname).toLowerCase())||String(f.mimetype).startsWith("audio/"))});app.use("/api/protected",requireAdmin);app.use((req,res,next)=>{if(req.path.startsWith("/api/")&&req.method!=="GET"&&req.path!=="/api/auth/login"&&req.path!=="/api/auth/check")return requireAdmin(req,res,next);next()});app.post("/api/music/upload",up.array("music",20),(q,s)=>s.json({success:true,files:(q.files||[]).map(f=>({name:f.filename,size:f.size,url:"/music/"+encodeURIComponent(f.filename)}))}));
app.use("/api/protected",requireAdmin);app.delete("/api/music/:filename",(q,s)=>{const n=path.basename(q.params.filename),p=path.join(MUSIC,n);if(!fs.existsSync(p))return s.status(404).json({success:false,error:"File not found"});autoDJ.removeMusic(n);s.json({success:true})});
app.use("/api/protected",requireAdmin);app.post("/api/ads/upload",media(ADS,"ads"),(q,s)=>s.json({success:true,files:(q.files||[]).map(f=>f.filename)}));app.use("/api/protected",requireAdmin);app.post("/api/jingles/upload",media(JINGLES,"jingles"),(q,s)=>s.json({success:true,files:(q.files||[]).map(f=>f.filename)}));
app.use("/api/admin",requireAdmin);app.post("/api/autodj/start",(q,s)=>{const ok=autoDJ.startAutoDJ();s.status(ok?200:409).json({success:ok,status:autoDJ.getStatus()})});app.post("/api/autodj/stop",(q,s)=>s.json({success:autoDJ.stopAutoDJ(),status:autoDJ.getStatus()}));app.post("/api/autodj/next",(q,s)=>s.json({success:autoDJ.next(),status:autoDJ.getStatus()}));app.post("/api/autodj/previous",(q,s)=>s.json({success:autoDJ.previous(),status:autoDJ.getStatus()}));app.post("/api/autodj/queue",(q,s)=>s.json({success:autoDJ.enqueue(q.body?.song),status:autoDJ.getStatus()}));app.post("/api/autodj/add",(q,s)=>s.json({success:autoDJ.addToPlaylist(q.body?.song),playlist:autoDJ.getPlaylist()}));app.post("/api/autodj/play",(q,s)=>{const ok=autoDJ.playNow(q.body?.song);s.status(ok?200:400).json({success:ok,status:autoDJ.getStatus(),error:ok?undefined:"Could not play this song now."})});app.post("/api/autodj/queue/clear",(q,s)=>{autoDJ.clearQueue();s.json({success:true,status:autoDJ.getStatus()})});app.get("/api/autodj/playlist",(q,s)=>s.json({success:true,playlist:autoDJ.getPlaylist()}));app.post("/api/autodj/playlist",(q,s)=>{const ok=autoDJ.setPlaylist(q.body?.playlist);if(ok&&autoDJ.getPlaylist().length&&(!autoDJ.getStatus().autoDJ)&&(!autoDJ.getStatus().live))autoDJ.startAutoDJ();s.status(ok?200:400).json({success:ok,playlist:autoDJ.getPlaylist(),status:autoDJ.getStatus(),error:ok?undefined:"Invalid playlist."})});app.post("/api/autodj/settings",(q,s)=>{const b=q.body||{},r={};if(b.shuffle!==undefined)r.shuffle=autoDJ.setShuffle(b.shuffle);if(b.repeat!==undefined)r.repeat=autoDJ.setRepeat(b.repeat);if(b.crossfade!==undefined)r.crossfade=autoDJ.setCrossfade(b.crossfade);if(b.gain!==undefined)r.gain=autoDJ.setGain(b.gain);if(b.adInterval!==undefined)r.adInterval=autoDJ.setAdInterval(b.adInterval);if(b.adTimes!==undefined)r.adTimes=autoDJ.setAdTimes(b.adTimes);s.json({success:true,settings:r,status:autoDJ.getStatus()})});app.post("/api/autodj/pause",(q,s)=>s.json({success:autoDJ.pause(),status:autoDJ.getStatus()}));app.post("/api/autodj/resume",(q,s)=>s.json({success:autoDJ.resume(),status:autoDJ.getStatus()}));app.post("/api/autodj/promotion",(q,s)=>{const ok=autoDJ.playPromotion();s.status(ok?200:409).json({success:ok,status:autoDJ.getStatus(),error:ok?undefined:"Promotion could not start. Start Auto DJ and upload an ad first."})});
app.get("/api/autodj/promotion/timer",(q,s)=>s.json({success:true,timer:autoDJ.getPromotionTimer()}));
app.post("/api/live/start",(q,s)=>{const ok=autoDJ.startLive();if(ok&&!live.start()){autoDJ.stopLive();return s.status(409).json({success:false,error:"Live source is busy"});}s.status(ok?200:409).json({success:ok,status:autoDJ.getStatus()})});app.post("/api/live/stop",(q,s)=>{live.stop();autoDJ.stopLive();s.json({success:true,status:autoDJ.getStatus()})});
app.get("/jonfm",(q,s)=>{s.statusCode=200;s.setHeader("Content-Type","audio/mpeg");s.setHeader("Cache-Control","no-cache,no-store,must-revalidate");s.setHeader("Connection","keep-alive");s.setHeader("Accept-Ranges","none");s.flushHeaders();broadcast.addClient(s);q.on("aborted",()=>{try{s.destroy()}catch{}})});
const server=http.createServer(app),wss=new WebSocketServer({noServer:true});server.on("upgrade",(req,socket,head)=>{try{if(new URL(req.url,"http://localhost").pathname!=="/live-mic")return socket.destroy()}catch{return socket.destroy()}wss.handleUpgrade(req,socket,head,ws=>wss.emit("connection",ws))});wss.on("connection",ws=>{if(!autoDJ.startLive()||!live.start()){ws.close(1013,"Live source unavailable");return}ws.on("message",d=>live.writeAudio(d));const done=()=>{live.stop();autoDJ.stopLive()};ws.on("close",done);ws.on("error",done)});
app.use((err,req,res,next)=>{console.error(err);res.status(400).json({success:false,error:err.message||"Request failed"})});server.listen(PORT,()=>{console.log("JON RADIO PLATFORM 2.0 listening on "+PORT);if(process.env.AUTO_DJ_AUTOSTART!=="false"){setTimeout(()=>{try{if(autoDJ.getMusicFiles().length)autoDJ.startAutoDJ()}catch(e){console.error("Auto DJ autostart failed:",e.message)}},1500)}});app.post("/api/autodj/jingle/settings",(req,res)=>{const ok=autoDJ.setJingleInterval(req.body?.intervalMinutes);res.status(ok?200:400).json({success:ok,status:autoDJ.getStatus()})});
app.get("/api/autodj/jingles",(_req,res)=>res.json({success:true,jingles:autoDJ.getJingles()}));
app.post("/api/autodj/jingle",(req,res)=>{const ok=autoDJ.playJingle();res.status(ok?200:409).json({success:ok,error:ok?undefined:"Jingle unavailable or Auto DJ inactive"});});
