const express=require("express"),multer=require("multer"),path=require("path"),fs=require("fs"),http=require("http"),{WebSocketServer}=require("ws");const autoDJ=require("./radio/autodj"),live=require("./radio/live"),broadcast=require("./radio/broadcast");
const app=express(),PORT=process.env.PORT||3000,ROOT=__dirname;app.use(express.json());app.use(express.urlencoded({extended:true}));app.use((req,res,next)=>{res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Methods","GET,POST,DELETE,OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type");if(req.method==="OPTIONS")return res.sendStatus(204);next()});
const MUSIC=path.join(ROOT,"music"),ADS=path.join(ROOT,"ads"),JINGLES=path.join(ROOT,"jingles");[MUSIC,ADS,JINGLES].forEach(d=>fs.mkdirSync(d,{recursive:true}));
function storage(dir){return multer.diskStorage({destination:dir,filename:(req,file,cb)=>{const safe=path.basename(file.originalname).replace(/[^a-zA-Z0-9._-]/g,"_");cb(null,Date.now()+"-"+safe)}})}
function media(dir,field){return multer({storage:storage(dir),limits:{fileSize:50*1024*1024},fileFilter:(r,f,cb)=>cb(null,[".mp3",".wav",".m4a"].includes(path.extname(f.originalname).toLowerCase())||String(f.mimetype).startsWith("audio/"))}).array(field,20)}
app.get("/health",(q,s)=>s.json({success:true,service:"JON RADIO PLATFORM",status:"ONLINE",version:"2.0"}));app.get("/",(q,s)=>s.json({platform:"JON RADIO PLATFORM",station:"JON FM ETHIOPIA",status:"ONLINE",version:"2.0"}));
app.use("/music",express.static(MUSIC));app.use("/ads",express.static(ADS));app.use("/jingles",express.static(JINGLES));
app.get("/api/status",(q,s)=>{const d=autoDJ.getStatus(),b=broadcast.status();s.json({station:"JON FM ETHIOPIA",online:b.running,live:d.live||live.isActive(),autoDJ:d.autoDJ,listeners:b.listeners,nowPlaying:d.nowPlaying,nextSong:d.nextSong,musicCount:d.musicCount,source:b.source})});
app.get("/api/music",(q,s)=>{const out=autoDJ.getMusicFiles().map(name=>{const st=fs.statSync(path.join(MUSIC,name));return{name,size:st.size,url:"/music/"+encodeURIComponent(name)}});s.json(out)});
const up=multer({storage:storage(MUSIC),limits:{fileSize:50*1024*1024},fileFilter:(r,f,cb)=>cb(null,[".mp3",".wav",".m4a"].includes(path.extname(f.originalname).toLowerCase())||String(f.mimetype).startsWith("audio/"))});app.post("/api/music/upload",up.array("music",20),(q,s)=>s.json({success:true,files:(q.files||[]).map(f=>({name:f.filename,size:f.size,url:"/music/"+encodeURIComponent(f.filename)}))}));
app.delete("/api/music/:filename",(q,s)=>{const n=path.basename(q.params.filename),p=path.join(MUSIC,n);if(!fs.existsSync(p))return s.status(404).json({success:false,error:"File not found"});autoDJ.removeMusic(n);s.json({success:true})});
app.post("/api/ads/upload",media(ADS,"ads"),(q,s)=>s.json({success:true,files:(q.files||[]).map(f=>f.filename)}));app.post("/api/jingles/upload",media(JINGLES,"jingles"),(q,s)=>s.json({success:true,files:(q.files||[]).map(f=>f.filename)}));
app.post("/api/autodj/start",(q,s)=>{const ok=autoDJ.startAutoDJ();s.status(ok?200:409).json({success:ok,status:autoDJ.getStatus()})});app.post("/api/autodj/stop",(q,s)=>s.json({success:autoDJ.stopAutoDJ(),status:autoDJ.getStatus()}));app.post("/api/autodj/next",(q,s)=>s.json({success:autoDJ.next(),status:autoDJ.getStatus()}));app.post("/api/autodj/previous",(q,s)=>s.json({success:autoDJ.previous(),status:autoDJ.getStatus()}));app.post("/api/autodj/queue",(q,s)=>s.json({success:autoDJ.enqueue(q.body?.song),status:autoDJ.getStatus()}));app.post("/api/autodj/add",(q,s)=>s.json({success:autoDJ.addToPlaylist(q.body?.song),playlist:autoDJ.getPlaylist()}));app.post("/api/autodj/play",(q,s)=>{const ok=autoDJ.enqueue(q.body?.song);if(ok)autoDJ.next();s.status(ok?200:400).json({success:ok,status:autoDJ.getStatus()})});app.post("/api/autodj/queue/clear",(q,s)=>{autoDJ.clearQueue();s.json({success:true,status:autoDJ.getStatus()})});app.get("/api/autodj/playlist",(q,s)=>s.json({success:true,playlist:autoDJ.getPlaylist()}));app.post("/api/autodj/playlist",(q,s)=>s.json({success:autoDJ.setPlaylist(q.body?.playlist),playlist:autoDJ.getPlaylist()}));app.post("/api/autodj/settings",(q,s)=>{const b=q.body||{},r={};if(b.shuffle!==undefined)r.shuffle=autoDJ.setShuffle(b.shuffle);if(b.repeat!==undefined)r.repeat=autoDJ.setRepeat(b.repeat);if(b.crossfade!==undefined)r.crossfade=autoDJ.setCrossfade(b.crossfade);if(b.gain!==undefined)r.gain=autoDJ.setGain(b.gain);if(b.adInterval!==undefined)r.adInterval=autoDJ.setAdInterval(b.adInterval);if(b.adTimes!==undefined)r.adTimes=autoDJ.setAdTimes(b.adTimes);s.json({success:true,settings:r,status:autoDJ.getStatus()})});app.post("/api/autodj/pause",(q,s)=>s.json({success:autoDJ.pause(),status:autoDJ.getStatus()}));app.post("/api/autodj/resume",(q,s)=>s.json({success:autoDJ.resume(),status:autoDJ.getStatus()}));app.post("/api/autodj/promotion",(q,s)=>{const ok=autoDJ.playPromotion();s.status(ok?200:409).json({success:ok,status:autoDJ.getStatus(),error:ok?undefined:"Promotion could not start. Start Auto DJ and upload an ad first."})});
app.post("/api/live/start",(q,s)=>{const ok=autoDJ.startLive();if(ok&&!live.start()){autoDJ.stopLive();return s.status(409).json({success:false,error:"Live source is busy"});}s.status(ok?200:409).json({success:ok,status:autoDJ.getStatus()})});app.post("/api/live/stop",(q,s)=>{live.stop();autoDJ.stopLive();s.json({success:true,status:autoDJ.getStatus()})});
app.get("/jonfm",(q,s)=>{s.setHeader("Content-Type","audio/mpeg");s.setHeader("Cache-Control","no-cache,no-store");s.flushHeaders();broadcast.addClient(s);q.on("close",()=>{try{s.end()}catch{}})});
const server=http.createServer(app),wss=new WebSocketServer({noServer:true});server.on("upgrade",(req,socket,head)=>{try{if(new URL(req.url,"http://localhost").pathname!=="/live-mic")return socket.destroy()}catch{return socket.destroy()}wss.handleUpgrade(req,socket,head,ws=>wss.emit("connection",ws))});wss.on("connection",ws=>{if(!autoDJ.startLive()||!live.start()){ws.close(1013,"Live source unavailable");return}ws.on("message",d=>live.writeAudio(d));const done=()=>{live.stop();autoDJ.stopLive()};ws.on("close",done);ws.on("error",done)});
app.use((err,req,res,next)=>{console.error(err);res.status(400).json({success:false,error:err.message||"Request failed"})});server.listen(PORT,()=>console.log("JON RADIO PLATFORM 2.0 listening on "+PORT));
