const{spawn}=require("child_process");const fs=require("fs"),path=require("path");const broadcast=require("./broadcast");
const MUSIC=path.join(__dirname,"..","music"),ADS=path.join(__dirname,"..","ads");let FFMPEG_PATH="ffmpeg";try{FFMPEG_PATH=require("ffmpeg-static")||FFMPEG_PATH}catch{}
let running=false,paused=false,live=false,wasRunningBeforeLive=false,proc=null,playlist=[],queue=[],index=0,shuffle=false,repeat=false,crossfade=0,gain=0,adInterval=0,lastAd=0,adTimes=[];let now=null,next=null,previous=null,generation=0;

const audioExt=[".mp3",".wav",".m4a"];
function files(dir=MUSIC){try{return fs.readdirSync(dir).filter(x=>audioExt.includes(path.extname(x).toLowerCase()))}catch{return[]}}
function load(){const f=files();playlist=playlist.filter(x=>f.includes(x));if(!playlist.length)playlist=f;return playlist.length>0}
function item(name,dir=MUSIC){const n=path.basename(String(name));return{name:n,filePath:path.join(dir,n)}}
function choose(){if(queue.length)return item(queue.shift());if(!playlist.length)return null;if(shuffle){let candidates=playlist.filter(x=>x!==now);if(!candidates.length)candidates=playlist;return item(candidates[Math.floor(Math.random()*candidates.length)])}if(index>=playlist.length){if(repeat)index=0;else return null}const x=playlist[index];index++;return item(x)}
function terminate(){generation++;if(proc){try{proc.kill("SIGTERM")}catch{}proc=null}}
function safeFile(song){try{return song&&fs.existsSync(song.filePath)}catch{return false}}
function playOne(song,g){if(!safeFile(song))return;const filters=[];if(gain!==0)filters.push("volume="+gain+"dB");const args=["-hide_banner","-loglevel","error","-re","-i",song.filePath,"-vn","-ac","2","-ar","44100","-b:a","128k"];if(filters.length)args.push("-af",filters.join(","));args.push("-f","mp3","pipe:1");proc=spawn(FFMPEG_PATH,args);proc.stdout.on("data",broadcast.broadcast);proc.on("error",()=>{if(g===generation)proc=null});proc.on("close",()=>{if(g!==generation)return;proc=null;if(running&&!paused&&!live)setTimeout(advance,50)})}
function playCrossfade(first,second,g){if(!safeFile(first)||!safeFile(second)){playOne(first,g);return}const d=Math.max(1,Math.min(Number(crossfade)||0,15));const filters=["acrossfade=d="+d+":c1=tri:c2=tri"];if(gain!==0)filters.push("volume="+gain+"dB");const args=["-hide_banner","-loglevel","error","-re","-i",first.filePath,"-re","-i",second.filePath,"-filter_complex","[0:a][1:a]"+filters[0]+"[a]"+(gain!==0?";[a]volume="+gain+"dB[out]":";[a]anull[out]"),"-map","[out]","-ac","2","-ar","44100","-b:a","128k","-f","mp3","pipe:1"];proc=spawn(FFMPEG_PATH,args);proc.stdout.on("data",broadcast.broadcast);proc.on("error",()=>{if(g===generation)proc=null});proc.on("close",()=>{if(g!==generation)return;proc=null;if(running&&!paused&&!live){previous=first.name;now=second.name;setTimeout(advance,50)}})}
function pickNextPreview(){if(queue.length)return queue[0];if(!playlist.length)return null;if(index>=playlist.length)return repeat?playlist[0]:null;if(shuffle)return playlist.find(x=>x!==now)||playlist[0];return playlist[index]}
function maybePromotion(){if(!running||live||paused||!adInterval)return false;const nowMs=Date.now();if(nowMs-lastAd<adInterval*60000)return false;const a=files(ADS);if(!a.length)return false;lastAd=nowMs;const ad=item(a[Math.floor(Math.random()*a.length)],ADS);terminate();now="PROMOTION: "+ad.name;playOne(ad,generation);return true}
function advance(){if(!running||paused||live)return;if(!load())return;if(maybePromotion())return;const song=choose();if(!song){running=false;broadcast.stop("autodj");return}previous=now;now=song.name;const upcoming=crossfade>0?choose():null;next=upcoming?upcoming.name:pickNextPreview();if(upcoming)playCrossfade(song,upcoming,generation);else playOne(song,generation)}
function startAutoDJ(){if(live)return false;if(running)return true;if(!load()||!broadcast.start("autodj"))return false;running=true;paused=false;lastAd=Date.now();advance();return true}
function stopAutoDJ(){running=false;paused=false;terminate();broadcast.stop("autodj");now=null;next=null;return true}
function startLive(){if(live)return true;wasRunningBeforeLive=running;if(running){running=false;terminate();broadcast.stop("autodj")}if(!broadcast.start("live")){if(wasRunningBeforeLive){running=true;broadcast.start("autodj");setTimeout(advance,100)}return false}live=true;return true}
function stopLive(){if(!live)return true;live=false;broadcast.stop("live");if(wasRunningBeforeLive&&!paused){running=true;if(broadcast.start("autodj"))setTimeout(advance,100)}wasRunningBeforeLive=false;return true}
function playNowSong(name){const n=path.basename(String(name||""));if(!files().includes(n)||live)return false;terminate();if(!running){if(!broadcast.start("autodj"))return false;running=true;paused=false}queue=queue.filter(x=>x!==n);previous=now;now=n;next=null;playOne(item(n),generation);return true}
function nextSong(){if(!running||live)return false;terminate();if(!load())return false;const s=choose();if(!s)return false;previous=now;now=s.name;next=pickNextPreview();playOne(s,generation);return true}
function previousSong(){if(!running||live||!previous)return false;const old=now;terminate();if(old)queue.unshift(old);const s=item(previous);now=s.name;next=pickNextPreview();playOne(s,generation);return true}
function setPlaylist(v){if(!Array.isArray(v))return false;const f=files();playlist=[...new Set(v.map(x=>path.basename(String(x))).filter(x=>f.includes(x)))];index=0;return true}
function addToPlaylist(v){const n=path.basename(String(v||""));if(!files().includes(n))return false;if(!playlist.includes(n))playlist.push(n);return true}
function setQueueSong(v){const n=path.basename(String(v||""));if(!files().includes(n))return false;queue.push(n);return true}
function clearQueue(){queue=[]}
function promotion(){if(!running||live||paused)return false;const a=files(ADS);if(!a.length)return false;terminate();const ad=item(a[Math.floor(Math.random()*a.length)],ADS);now="PROMOTION: "+ad.name;playOne(ad,generation);return true}
function status(){return{autoDJ:running,live,paused,nowPlaying:now,nextSong:next,previousSong:previous,musicCount:files().length,playlist:playlist.slice(),queue:queue.slice(),shuffle,repeat,crossfade,gain,adInterval,adTimes}}
module.exports={getMusicFiles:()=>files(),startAutoDJ,stopAutoDJ,startLive,stopLive,next:nextSong,previous:previousSong,setPlaylist,getPlaylist:()=>playlist.slice(),addToPlaylist,enqueue:setQueueSong,clearQueue,setShuffle:v=>{shuffle=!!v;return true},setRepeat:v=>{repeat=!!v;return true},setCrossfade:v=>{const n=Number(v);if(!Number.isFinite(n)||n<0||n>15)return false;crossfade=n;return true},setGain:v=>{const n=Number(v);if(!Number.isFinite(n)||n<-12||n>12)return false;gain=n;return true},setAdInterval:v=>{const n=Number(v);if(!Number.isFinite(n)||n<0||n>240)return false;adInterval=n;return true},setAdTimes:v=>{if(!Array.isArray(v))return false;adTimes=[...new Set(v.map(x=>String(x)).filter(x=>/^([01]\\d|2[0-3]):[0-5]\\d$/.test(x)))];return true},playPromotion:promotion,playNow:playNowSong,removeMusic:n=>{const p=path.join(MUSIC,path.basename(String(n)));if(fs.existsSync(p))fs.unlinkSync(p);load();return true},getStatus:status,pause:()=>{if(!proc||!running||paused)return false;try{process.kill(proc.pid,"SIGSTOP");paused=true;return true}catch{return false}},resume:()=>{if(!proc||!paused)return false;try{process.kill(proc.pid,"SIGCONT");paused=false;return true}catch{return false}}};
