const{spawn}=require("child_process");const fs=require("fs"),path=require("path");const broadcast=require("./broadcast");
const MEDIA_ROOT=process.env.MEDIA_ROOT?path.resolve(process.env.MEDIA_ROOT):path.join(__dirname,"..");const MUSIC=path.join(MEDIA_ROOT,"music"),ADS=path.join(MEDIA_ROOT,"ads"),JINGLES=path.join(MEDIA_ROOT,"jingles");let FFMPEG_PATH=require("ffmpeg-static")||"ffmpeg";
const CONTINUOUS=process.env.AUTO_DJ_CONTINUOUS!=="false";let running=false,paused=false,live=false,wasRunningBeforeLive=false,proc=null,pending=null,playlist=[],queue=[],index=0,shuffle=false,repeat=false,crossfade=0,gain=0,adInterval=0,lastAd=0,adTimes=[],jingleInterval=0,lastJingle=0;let now=null,next=null,previous=null,generation=0,breakRequest=null;
const audioExt=[".mp3",".wav",".m4a"],DIR_CACHE_MS=2000,PREFETCH_BYTES=1024*1024,STARTUP_BUFFER_BYTES=64*1024;let dirCache=new Map();
function files(dir=MUSIC){const key=dir,hit=dirCache.get(key),t=Date.now();if(hit&&t-hit.time<DIR_CACHE_MS)return hit.list.slice();let list=fs.readdirSync(dir).filter(x=>audioExt.includes(path.extname(x).toLowerCase()));dirCache.set(key,{time:t,list});return list.slice()}
function invalidateFiles(dir=MUSIC){dirCache.delete(dir)}
function load(){const f=files();playlist=playlist.filter(x=>f.includes(x));if(!playlist.length)playlist=f;return playlist.length>0}
function item(name,dir=MUSIC){const n=path.basename(String(name));return{name:n,filePath:path.join(dir,n)}}
function choose(){if(queue.length)return item(queue.shift());if(!playlist.length)return null;if(shuffle){let candidates=playlist.filter(x=>x!==now);if(!candidates.length)candidates=playlist;return item(candidates[Math.floor(Math.random()*candidates.length)])}if(index>=playlist.length){if(repeat||CONTINUOUS)index=0;else return null}const x=playlist[index];index++;return item(x)}
function killProcess(p){if(p&&p.pid){try{p.kill("SIGTERM")}catch(e){}}}function terminate(){generation++;killProcess(proc);killProcess(pending&&pending.proc);proc=null;pending=null}
function safeFile(song){return !!(song&&fs.existsSync(song.filePath))}
function encoderArgs(song){const filters=[];if(gain!==0)filters.push("volume="+gain+"dB");const args=["-hide_banner","-loglevel","error","-nostdin","-re","-i",song.filePath,"-vn","-ac","2","-ar","44100","-b:a","128k"];if(filters.length)args.push("-af",filters.join(","));args.push("-f","mp3","pipe:1");return args}
function startPrefetch(song,g){if(!safeFile(song)||g!==generation)return null;const p=spawn(FFMPEG_PATH,encoderArgs(song),{stdio:["ignore","pipe","ignore"]});const state={song,proc:p,buffer:[],bytes:0,streaming:false,paused:false,done:false};p.stdout.on("data",chunk=>{if(state.streaming){broadcast.broadcast(chunk);return}state.buffer.push(chunk);state.bytes+=chunk.length;if(!state.paused&&state.bytes>=PREFETCH_BYTES){try{p.kill("SIGSTOP");state.paused=true}catch(e){}}});p.on("error",()=>{state.done=true;if(pending===state)pending=null});p.on("close",()=>{state.done=true});return state}
function usePending(g){const state=pending;if(!state||!state.song||g!==generation)return null;pending=null;for(const chunk of state.buffer)broadcast.broadcast(chunk);state.buffer=[];state.bytes=0;if(state.done){proc=null;return state.song}proc=state.proc;state.streaming=true;if(state.paused){try{process.kill(proc.pid,"SIGCONT");state.paused=false}catch(e){state.done=true;proc=null;return null}}proc.on("error",()=>{if(g===generation)proc=null});proc.on("close",()=>{if(g!==generation)return;proc=null;if(running&&!paused&&!live)setTimeout(advance,0)});return state.song}
function playPrimed(song,g){if(!safeFile(song)){if(g===generation&&running&&!paused&&!live)setTimeout(advance,0);return;}const p=spawn(FFMPEG_PATH,encoderArgs(song),{stdio:["ignore","pipe","ignore"]});proc=p;let buffer=[],bytes=0,started=false;const flush=()=>{if(started)return;started=true;for(const chunk of buffer)broadcast.broadcast(chunk);buffer=[];};p.stdout.on("data",chunk=>{if(started){broadcast.broadcast(chunk);return}buffer.push(chunk);bytes+=chunk.length;if(bytes>=STARTUP_BUFFER_BYTES)flush()});p.on("error",()=>{if(g===generation)proc=null});p.on("close",()=>{if(g!==generation)return;if(!started)flush();proc=null;if(running&&!paused&&!live)setTimeout(advance,0)});const upcoming=choose();next=upcoming?upcoming.name:pickNextPreview();pending=upcoming?startPrefetch(upcoming,g):null}
function playOne(song,g,prefetch=false){if(!safeFile(song)){if(g===generation&&running&&!paused&&!live)setTimeout(advance,0);return;}const p=spawn(FFMPEG_PATH,encoderArgs(song),{stdio:["ignore","pipe","ignore"]});proc=p;p.stdout.on("data",broadcast.broadcast);p.on("error",()=>{if(g===generation)proc=null});p.on("close",()=>{if(g!==generation)return;proc=null;if(running&&!paused&&!live)setTimeout(advance,0)});if(prefetch){const upcoming=choose();next=upcoming?upcoming.name:pickNextPreview();pending=upcoming?startPrefetch(upcoming,g):null}}
function playCrossfade(first,second,g){if(!safeFile(first)||!safeFile(second)){playOne(first,g);return}const d=Math.max(1,Math.min(Number(crossfade)||0,15));const args=["-hide_banner","-loglevel","error","-nostdin","-re","-i",first.filePath,"-re","-i",second.filePath,"-filter_complex","[0:a][1:a]acrossfade=d="+d+":c1=tri:c2=tri[a];[a]volume="+gain+"dB[out]","-map","[out]","-ac","2","-ar","44100","-b:a","128k","-f","mp3","pipe:1"];if(gain===0)args[args.indexOf("-filter_complex")+1]="[0:a][1:a]acrossfade=d="+d+":c1=tri:c2=tri[out]";proc=spawn(FFMPEG_PATH,args,{stdio:["ignore","pipe","ignore"]});proc.stdout.on("data",broadcast.broadcast);proc.on("error",()=>{if(g===generation)proc=null});proc.on("close",()=>{if(g!==generation)return;proc=null;if(running&&!paused&&!live){previous=first.name;now=second.name;setTimeout(advance,50)}})}
function pickNextPreview(){if(queue.length)return queue[0];if(!playlist.length)return null;if(index>=playlist.length)return repeat?playlist[0]:null;if(shuffle)return playlist.find(x=>x!==now)||playlist[0];return playlist[index]}
function maybeJingle(){if(!running||live||paused||!jingleInterval)return false;const nowMs=Date.now();if(nowMs-lastJingle<jingleInterval*60000)return false;const a=files(JINGLES);if(!a.length)return false;lastJingle=nowMs;breakRequest={type:"jingle"};return true}
function maybePromotion(){if(!running||live||paused||!adInterval)return false;const nowMs=Date.now();if(nowMs-lastAd<adInterval*60000)return false;const a=files(ADS);if(!a.length)return false;lastAd=nowMs;breakRequest={type:"promotion"};return true}
function promotionTimer(){return adInterval>0?{enabled:true,intervalMinutes:adInterval,nextAt:new Date(lastAd+adInterval*60000).toISOString()}:{enabled:false,intervalMinutes:0,nextAt:null}}
setInterval(()=>{if(!running||paused||live)return;if(!proc){setTimeout(()=>{if(running&&!paused&&!live&&!proc)advance()},0);return}if(maybeJingle())return;maybePromotion()},1000);
function advance(){if(!running||paused||live)return;if(!load())return;if(breakRequest){const req=breakRequest;breakRequest=null;const a=req.type==="jingle"?files(JINGLES):files(ADS);if(a.length){const x=item(a[Math.floor(Math.random()*a.length)],req.type==="jingle"?JINGLES:ADS);previous=now;now=(req.type==="jingle"?"JINGLE: ":"PROMOTION: ")+x.name;playOne(x,generation);return}}if(crossfade<=0&&pending&&pending.song){const started=usePending(generation);if(started){previous=now;now=started.name;const upcoming=choose();pending=upcoming?startPrefetch(upcoming,generation):null;next=upcoming?upcoming.name:pickNextPreview();return}}const song=choose();if(!song){running=false;broadcast.stop("autodj");now=null;next=null;return}previous=now;now=song.name;const upcoming=crossfade>0&&playlist.length>1?choose():null;next=upcoming?upcoming.name:pickNextPreview();if(upcoming)playCrossfade(song,upcoming,generation);else playOne(song,generation,crossfade<=0)}
function startAutoDJ(){if(live)return false;if(running)return true;if(!load()||!broadcast.start("autodj"))return false;running=true;paused=false;lastAd=Date.now();lastJingle=Date.now();const g=generation;const first=choose();if(!first){running=false;broadcast.stop("autodj");return false}previous=now;now=first.name;next=pickNextPreview();playPrimed(first,g);return true}
function stopAutoDJ(){running=false;paused=false;breakRequest=null;terminate();broadcast.stop("autodj");now=null;next=null;previous=null;return true}
function startLive(){if(live)return true;wasRunningBeforeLive=running;if(running){running=false;terminate();broadcast.stop("autodj")}if(!broadcast.start("live")){if(wasRunningBeforeLive){running=true;broadcast.start("autodj");setTimeout(advance,100)}return false}live=true;return true}
function stopLive(){if(!live)return true;live=false;broadcast.stop("live");if(wasRunningBeforeLive&&!paused){running=true;if(broadcast.start("autodj"))setTimeout(advance,100)}wasRunningBeforeLive=false;return true}
function playNowSong(name){const n=path.basename(String(name||""));if(!files().includes(n)||live)return false;terminate();if(!running){if(!broadcast.start("autodj"))return false;running=true;paused=false;lastAd=Date.now();lastJingle=Date.now()}queue=queue.filter(x=>x!==n);previous=now;now=n;next=pickNextPreview();playOne(item(n),generation);return true}
function nextSong(){if(!running||live)return false;if(!load())return false;const g=++generation;const current=proc;proc=null;if(current&&current.stdout){try{current.stdout.removeAllListeners("data")}catch(e){}}if(current&&current.pid){try{current.kill("SIGINT")}catch(e){}}const handoff=()=>{if(g!==generation||!running||paused||live)return;if(crossfade<=0&&pending&&pending.song){const started=usePending(g);if(started){previous=now;now=started.name;const upcoming=choose();pending=upcoming?startPrefetch(upcoming,g):null;next=upcoming?upcoming.name:pickNextPreview();return}pending=null}const s=choose();if(!s)return;previous=now;now=s.name;next=pickNextPreview();playOne(s,g)};setTimeout(handoff,120);return true}
function previousSong(){if(!running||live||!previous)return false;const old=now;terminate();if(old)queue.unshift(old);const s=item(previous);now=s.name;next=pickNextPreview();playOne(s,generation);return true}
function setPlaylist(v){if(!Array.isArray(v))return false;const f=files();playlist=[...new Set(v.map(x=>path.basename(String(x))).filter(x=>f.includes(x)))];if(!playlist.length){index=0;next=null;return true}const current=now&&playlist.indexOf(now);index=current>=0?current+1:0;if(!running&&!live){if(!broadcast.start("autodj"))return false;running=true;paused=false;lastAd=Date.now();lastJingle=Date.now();advance()}else if(running&&!live&&!proc&&!paused){advance()}return true}
function addToPlaylist(v){const n=path.basename(String(v||""));if(!files().includes(n))return false;if(!playlist.includes(n))playlist.push(n);if(!running&&!live){if(!broadcast.start("autodj"))return false;running=true;paused=false;lastAd=Date.now();lastJingle=Date.now();index=Math.max(0,playlist.indexOf(n));advance()}return true}
function setQueueSong(v){const n=path.basename(String(v||""));if(!files().includes(n))return false;queue.push(n);return true}
function clearQueue(){queue=[]}
function getJingles(){return files(JINGLES)}
function playJingle(){if(!running||live||paused)return false;const a=files(JINGLES);if(!a.length)return false;breakRequest={type:"jingle"};if(!proc)advance();return true}
function promotion(){if(!running||live||paused)return false;const a=files(ADS);if(!a.length)return false;breakRequest={type:"promotion"};if(!proc)advance();return true}
function status(){return{autoDJ:running,live,paused,nowPlaying:now,nextSong:next,previousSong:previous,musicCount:files().length,jingleCount:files(JINGLES).length,playlist:playlist.slice(),queue:queue.slice(),shuffle,repeat,crossfade,gain,adInterval,jingleInterval,adTimes}}
module.exports={getMusicFiles:()=>files(),startAutoDJ,stopAutoDJ,startLive,stopLive,next:nextSong,previous:previousSong,setPlaylist,getPlaylist:()=>playlist.slice(),addToPlaylist,enqueue:setQueueSong,clearQueue,setShuffle:v=>{shuffle=!!v;return true},setRepeat:v=>{repeat=!!v;return true},setCrossfade:v=>{const n=Number(v);if(!Number.isFinite(n)||n<0||n>15)return false;crossfade=n;return true},setGain:v=>{const n=Number(v);if(!Number.isFinite(n)||n<-12||n>12)return false;gain=n;return true},setAdInterval:v=>{const n=Number(v);if(!Number.isFinite(n)||n<0||n>240)return false;adInterval=n;return true},setJingleInterval:v=>{const n=Number(v);if(!Number.isFinite(n)||n<0||n>240)return false;jingleInterval=n;return true},setAdTimes:v=>{if(!Array.isArray(v))return false;adTimes=[...new Set(v.map(x=>String(x)).filter(x=>/^([01]\\d|2[0-3]):[0-5]\\d$/.test(x)))];return true},playPromotion:promotion,playJingle,getJingles,playNow:playNowSong,removeMusic:n=>{const p=path.join(MUSIC,path.basename(String(n)));if(fs.existsSync(p))fs.unlinkSync(p);invalidateFiles(MUSIC);load();return true},getPromotionTimer:promotionTimer,getStatus:status,pause:()=>{if(!proc||!running||paused)return false;process.kill(proc.pid,"SIGSTOP");paused=true;return true},resume:()=>{if(!proc||!paused)return false;process.kill(proc.pid,"SIGCONT");paused=false;return true}};
