const{spawn}=require("child_process");const fs=require("fs"),path=require("path");const broadcast=require("./broadcast");
const MUSIC=path.join(__dirname,"..","music"),ADS=path.join(__dirname,"..","ads");let FFMPEG_PATH="ffmpeg";try{FFMPEG_PATH=require("ffmpeg-static")||FFMPEG_PATH}catch{}
let running=false,paused=false,live=false,proc=null,playlist=[],queue=[],index=0,now=null,next=null,previous=null,shuffle=false,repeat=false,crossfade=0,gain=0,adInterval=0,lastAd=0,adTimes=[];let generation=0;
function files(){try{return fs.readdirSync(MUSIC).filter(x=>[".mp3",".wav",".m4a"].includes(path.extname(x).toLowerCase()))}catch{return[]}}
function load(){const f=files();playlist=playlist.filter(x=>f.includes(x));if(!playlist.length)playlist=f;return playlist.length>0}
function item(name){return{name,filePath:path.join(MUSIC,name)}}
function choose(){if(queue.length)return queue.shift();if(!playlist.length)return null;if(shuffle)index=Math.floor(Math.random()*playlist.length);const x=playlist[index];index=(index+1)%playlist.length;return item(x)}
function terminate(){generation++;if(proc){try{proc.kill("SIGTERM")}catch{}proc=null}}
function playOne(song,g){if(!song)return;proc=spawn(FFMPEG_PATH,["-hide_banner","-loglevel","error","-re","-i",song.filePath,"-vn","-ac","2","-ar","44100","-b:a","128k","-af",`volume=${gain}dB`,"-f","mp3","pipe:1"]);proc.stdout.on("data",broadcast.broadcast);proc.on("error",()=>{if(g===generation)proc=null});proc.on("close",()=>{if(g!==generation)return;proc=null;if(running&&!paused&&!live)setTimeout(advance,50)})}
function advance(){if(!running||paused||live)return;if(!load())return;const song=choose();if(!song)return;previous=now;now=song.name;next=playlist.length>1?playlist[index]:null;const g=generation;playOne(song,g)}
function startAutoDJ(){if(live||running)return running;if(!load()||!broadcast.start("autodj"))return false;running=true;paused=false;lastAd=Date.now();advance();return true}
function stopAutoDJ(){running=false;paused=false;terminate();broadcast.stop("autodj");now=null;next=null;return true}
function startLive(){if(live)return true;if(running){terminate();broadcast.stop("autodj")}if(!broadcast.start("live"))return false;live=true;return true}
function stopLive(){if(!live)return true;live=false;broadcast.stop("live");if(running&&!paused){if(broadcast.start("autodj")){setTimeout(advance,100)}}return true}
function nextSong(){if(!running||live)return false;terminate();const s=choose();if(!s)return false;previous=now;now=s.name;next=playlist[index]||null;playOne(s,generation);return true}
function previousSong(){if(!running||live||!previous)return false;terminate();queue.unshift(now);const s=item(previous);now=s.name;playOne(s,generation);return true}
function setPlaylist(v){if(!Array.isArray(v))return false;const f=files();playlist=[...new Set(v.map(x=>path.basename(String(x))).filter(x=>f.includes(x)))];if(!playlist.length)playlist=f;index=0;return true}
function setQueueSong(v){const n=path.basename(String(v||""));if(!files().includes(n))return false;queue.push(n);return true}
function status(){return{autoDJ:running,live,paused,nowPlaying:now,nextSong:next,previousSong:previous,musicCount:files().length,playlist,queue,shuffle,repeat,crossfade,gain,adInterval,adTimes}}
module.exports={getMusicFiles:files,startAutoDJ,stopAutoDJ,startLive,stopLive,next:nextSong,previous:previousSong,setPlaylist,getPlaylist:()=>playlist.slice(),enqueue:setQueueSong,clearQueue:()=>{queue=[]},setShuffle:v=>shuffle=!!v,setRepeat:v=>repeat=!!v,setCrossfade:v=>{const n=Number(v);if(!Number.isFinite(n)||n<0||n>15)return false;crossfade=n;return true},setGain:v=>{const n=Number(v);if(!Number.isFinite(n)||n<-12||n>12)return false;gain=n;return true},setAdInterval:v=>{const n=Number(v);if(!Number.isFinite(n)||n<0||n>240)return false;adInterval=n;return true},setAdTimes:v=>{if(!Array.isArray(v))return false;adTimes=[...new Set(v.filter(x=>/^([01]\\d|2[0-3]):[0-5]\\d$/.test(String(x))))];return true},playPromotion:()=>{if(!running||live||paused)return false;let a=[];try{a=fs.readdirSync(ADS).filter(x=>[".mp3",".wav",".m4a"].includes(path.extname(x).toLowerCase()))}catch{}if(!a.length)return false;terminate();const ad=item(a[Math.floor(Math.random()*a.length)]);ad.filePath=path.join(ADS,ad.name);const g=generation;const old=running;now="PROMOTION: "+ad.name;playOne(ad,g);return old},removeMusic:n=>{const p=path.join(MUSIC,path.basename(String(n)));if(fs.existsSync(p))fs.unlinkSync(p);load();return true},getStatus:status,pause:()=>{if(!proc||!running||paused)return false;try{process.kill(proc.pid,"SIGSTOP");paused=true;return true}catch{return false}},resume:()=>{if(!proc||!paused)return false;try{process.kill(proc.pid,"SIGCONT");paused=false;return true}catch{return false}}};
